### ISSUE TITLE
Error on Widget Start

### ISSUE THREAD

**Issue by cazarottiv** [centreon/centreon-widget-global-health#3]
Hi. The widget is not working on centreon 2.8.3.

The error log is:

PHP Fatal error:  Call to undefined method CentreonSession::session_start() in /usr/share/centreon/www/widgets/global-health/src/global_health.php on line 52

Its working on 2.7.8, so I´m pretty shure that this is a compatibility problem.
Could you please fix?

Thanks.
Vicente

**Comment by lpinsivy** [comment]
Should be work with latest versions of Centreon Web 2.8.x because I can't reproduce error

**Comment by lpinsivy** [comment]
commit abea6f6 a4e4172
